# Generated by Django 5.2.3 on 2025-06-21 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cliente'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
